# Generated by Django 4.2.18 on 2025-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='librarian',
            name='name',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='library',
            name='name',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
